### PR TITLE
wrong params and headers type

### PR DESCRIPTION
**Pull request by asoseil**
There was an error with the type

### CODE REVIEW

**Comment by nitaigao** [comment]
Hi any movement on this? We will have to fork this repo because it's blocking progress.

**Comment by AbM7797** [comment]
We have the same issue for params in CreateEmailCampaign struct, it need to be changed also to map[string]string

**Comment by iwittkau** [comment]
`*interface{}` really makes no sense.

I was however able to do this:

```go
func toInterfacePointer(i interface{}) *interface{} {
	return &i
}
```

```go
headers := make(map[string]interface{})
// add headers
var msg lib.SendSmtpEmail
msg.Headers = toInterfacePointer(headers)
```

**Comment by LandazuriPaul** [comment]
This has been fixed with #30. The PR also fixed the `incompatible` go module situation.

So to upgrade to the latest fixed version, replace your imports with `github.com/sendinblue/APIv3-go-library/v2` (the `v2` suffix is key) and install the v2 with:

```bash
go get -u github.com/sendinblue/APIv3-go-library/v2
go mod tidy
```

**Pull request closed without merging**
