### PR TITLE
change param type

### PR DESCRIPTION
**Pull request by AbM7797**

### CODE REVIEW

**Comment by canardaaydin** [comment]
waiting for this for to be merged

**Comment by jain-raunak** [comment]
> waiting for this for to be merged

Hi @canardaaydin 
Sorry for the delay, please create a branch from this project and use it. Meanwhile we are working to upgrade this project with all the changes and fixes.
Apologies for the inconveniences!

**Comment by iwittkau** [comment]
Intermediate fix:

```go
func toInterfacePointer(i interface{}) *interface{} {
	return &i
}
```

```go
headers := make(map[string]interface{})
// add headers
var msg lib.SendSmtpEmail
msg.Headers = toInterfacePointer(headers)
```

**Comment by jain-raunak** [comment]
This has been fixed in the latest version. Also to upgrade to the latest fixed version, replace your imports with github.com/sendinblue/APIv3-go-library/v2 (the v2 suffix is key) and install the v2 with:

```
go get -u github.com/sendinblue/APIv3-go-library/v2/lib
go mod tidy
```

Hence, closing the PR.

**Pull request closed without merging**
