### PR TITLE
AST-9: go wrapper update

### PR DESCRIPTION
**Pull request by jain-raunak**
- After generation, need to make changes for datatype *interface{} to map[string]interface{}
- Change in folder structure as per https://go.dev/blog/v2-go-modules to upgrade the version
- Rest all changes are due to generation only

### CODE REVIEW

**Review by shubhamUpadhyayInBlue — DISMISSED** [review]
LGTM

**Review by shubhamUpadhyayInBlue — DISMISSED** [review]

**Comment by Wazazaby** [comment]
Shouldn't the module path [here](https://github.com/sendinblue/APIv3-go-library/blob/feature_AST-9/go.mod) be `github.com/sendinblue/APIv3-go-library/v3` instead of `v3` ?

**Comment by jain-raunak** [comment]
> Shouldn't the module path [here](https://github.com/sendinblue/APIv3-go-library/blob/feature_AST-9/go.mod#L1) be `github.com/sendinblue/APIv3-go-library/v3` instead of `v3` ?

Thanks @Wazazaby for pointing this out as it got missed while changing the folder structure. It should be github.com/sendinblue/APIv3-go-library/lib as per the current structure.

**Comment by Wazazaby** [comment]
Hmm no, the main module's module path should be `github.com/sendinblue/APIv3-go-library/v3`, and then the `/lib` comes from the sub package. When using it, it will look like this in an import : `import sib github.com/sendinblue/APIv3-go-library/v3/lib`

**Comment by jain-raunak** [comment]
> Hmm no, the main module's module path should be `github.com/sendinblue/APIv3-go-library/v3`, and then the `/lib` comes from the sub package. When using it, it will look like this as an import statement : `import sib github.com/sendinblue/APIv3-go-library/v3/lib`

Is there any specific reason for your suggestion of keeping v3 as main folder?
Because here we are not changing the current structure and making a feature release with fixes. So import path would be same as `github.com/sendinblue/APIv3-go-library/lib`

**Comment by Wazazaby** [comment]
When you're updating a library to a new major version, the module's module path should contain the major version number ([you can read more about this here, at the bottom](https://go.dev/doc/modules/major-version)). Having `/v3` in the path doesn't mean you have to put your library in a `v3` subfolder.

**Comment by jain-raunak** [comment]
> When you're updating a library to a new major version, the module's module path should contain the major version number ([you can read more about this here, at the bottom](https://go.dev/doc/modules/major-version)). Having `/v3` in the path doesn't mean you have to put your library in a `v3` subfolder.

Hi @Wazazaby 
Point well taken but here it is not a major version release. It would be a feature release with new tag version as 2.1.0(earlier it was 2.0.1) so no change would be required in module path.

**Comment by Wazazaby** [comment]
@jain-raunak amazing 🙏 thank you

**Review by shubhamUpadhyayInBlue — APPROVED** [review]
LGTM

**Pull request merged**
